
/******************************************************************************
DO NOT EDIT THIS FILE!  THIS FILE WAS GENERATED BY GNAST
FROM THE TEMPLATE FILE AstClass.vm.
ANY MODIFICATIONS TO THIS FILE WILL BE LOST UPON REGENERATION.

-------------------------------------------------------------------------------

Copyright 2003, 2004, 2005 Mark Utting
This file is part of the czt project.

The czt project contains free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

The czt project is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with czt; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
******************************************************************************/

package net.sourceforge.czt.tcoz.impl;

import java.util.*;
import java.util.logging.*;

import net.sourceforge.czt.base.ast.*;
import net.sourceforge.czt.base.impl.*;
import net.sourceforge.czt.base.visitor.*;
import net.sourceforge.czt.util.Visitor;
import net.sourceforge.czt.z.ast.*;
import net.sourceforge.czt.z.impl.*;
import net.sourceforge.czt.oz.ast.*;
import net.sourceforge.czt.oz.impl.*;
import net.sourceforge.czt.tcoz.ast.*;
import net.sourceforge.czt.tcoz.visitor.*;

import net.sourceforge.czt.tcoz.visitor.AtProExprVisitor;

/**
 * An implementation of the interface
 * {@link AtProExpr}.
 *
 * @author Gnast version 0.1
 */
public class AtProExprImpl
  extends OpExprImpl   implements AtProExpr
{
  /**
   * The default constructor.
   *
   * Do not use it explicitly, unless you are extending this class.
   * If you want to create an instance of this class, please use the
   * {@link net.sourceforge.czt.tcoz.ast.TcozFactory object factory}.
   */
  protected AtProExprImpl()
  {
  }

  protected AtProExprImpl(BaseFactory factory)
  {
    super(factory);
  }

  /**
   * Compares the specified object with this AtProExprImpl
   * for equality.  Returns true if and only if the specified object is
   * also a(n) AtProExprImpl and all the getter methods except getAnns
   * return equal objects.
   */
  public boolean equals(Object obj)
  {
    if (obj != null) {
      if (this.getClass().equals(obj.getClass()) && super.equals(obj)) {
        AtProExprImpl object = (AtProExprImpl) obj;
        if (event_ != null) {
          if (!event_.equals(object.event_)) {
            return false;
          }
        }
        else {
          if (object.event_ != null) {
            return false;
          }
        }
        if (expr_ != null) {
          if (!expr_.equals(object.expr_)) {
            return false;
          }
        }
        else {
          if (object.expr_ != null) {
            return false;
          }
        }
        if (opExpr_ != null) {
          if (!opExpr_.equals(object.opExpr_)) {
            return false;
          }
        }
        else {
          if (object.opExpr_ != null) {
            return false;
          }
        }
        return true;
      }
    }
    return false;
  }

  /**
   * Returns the hash code value for this AtProExprImpl.
   */
  public int hashCode()
  {
    final int constant = 31;

    int hashCode = super.hashCode();
    hashCode += "AtProExprImpl".hashCode();
    if (event_ != null) {
      hashCode += constant * event_.hashCode();
    }
    if (expr_ != null) {
      hashCode += constant * expr_.hashCode();
    }
    if (opExpr_ != null) {
      hashCode += constant * opExpr_.hashCode();
    }
    return hashCode;
  }

  /**
   * Accepts a visitor.
   */
  public <R> R accept(net.sourceforge.czt.util.Visitor<R> v)
  {
    if (v instanceof AtProExprVisitor) {
      AtProExprVisitor<R> visitor = (AtProExprVisitor<R>) v;
      return visitor.visitAtProExpr(this);
    }
    return super.accept(v);
  }

  /**
   * Returns a new object of this class.
   */
  public AtProExprImpl create(Object[] args)
  {
    AtProExprImpl zedObject = null;
    try {
      Event event = (Event) args[0];
      net.sourceforge.czt.z.ast.Expr expr = (net.sourceforge.czt.z.ast.Expr) args[1];
      net.sourceforge.czt.oz.ast.OpExpr opExpr = (net.sourceforge.czt.oz.ast.OpExpr) args[2];
      zedObject = new AtProExprImpl(getFactory());
      zedObject.setEvent(event);
      zedObject.setExpr(expr);
      zedObject.setOpExpr(opExpr);
    }
    catch (IndexOutOfBoundsException e) {
      throw new IllegalArgumentException();
    }
    catch (ClassCastException e) {
      throw new IllegalArgumentException();
    }
    return zedObject;
  }

  public Object[] getChildren()
  {
    Object[] erg = { getEvent(), getExpr(), getOpExpr() };
    return erg;
  }

  private Event event_;

  public Event getEvent()
  {
    return event_;
  }

  public void setEvent(Event event)
  {
    event_ = event;
  }

  private net.sourceforge.czt.z.ast.Expr expr_;

  public net.sourceforge.czt.z.ast.Expr getExpr()
  {
    return expr_;
  }

  public void setExpr(net.sourceforge.czt.z.ast.Expr expr)
  {
    expr_ = expr;
  }

  private net.sourceforge.czt.oz.ast.OpExpr opExpr_;

  public net.sourceforge.czt.oz.ast.OpExpr getOpExpr()
  {
    return opExpr_;
  }

  public void setOpExpr(net.sourceforge.czt.oz.ast.OpExpr opExpr)
  {
    opExpr_ = opExpr;
  }
}
