
/*
THIS FILE WAS GENERATED BY GNAST.
ANY MODIFICATIONS TO THIS FILE WILL BE LOST UPON REGENERATION.

************************************************************

Copyright 2003 Mark Utting
This file is part of the czt project.

The czt project contains free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

The czt project is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with czt; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

package net.sourceforge.czt.z.impl;

import java.util.*;
import java.util.logging.*;

import net.sourceforge.czt.base.impl.*;
import net.sourceforge.czt.z.ast.*;
import net.sourceforge.czt.z.visitor.*;

import net.sourceforge.czt.z.visitor.CondExprVisitor;

/**
 * An implementation of the interface
 * {@link CondExpr}.
 *
 * @author Gnast version 0.1
 */
public class CondExprImpl
extends ExprImpl implements CondExpr
{
  /**
   * The default constructor.
   *
   * Do not use it explicitly, unless you are extending this class.
   * If you want to create an instance of this class, please use the
   * {@link CoreFactory object factory}.
   */
  protected CondExprImpl() { }

  /**
   * Compares the specified object with this CondExprImpl
   * for equality.  Returns true if and only if the specified object is
   * also a(n) CondExprImpl and all the getter methods except getAnns
   * return equal objects.
   */
  public boolean equals(Object obj)
  {
    if(obj != null &&
       this.getClass().equals(obj.getClass()) &&
       super.equals(obj)) {
      CondExprImpl object = (CondExprImpl) obj;
      if((mPred == null && object.mPred != null) ||
         (mPred != null &&
         ! mPred.equals(object.mPred))) return false;
      if(mPred == null && object.mPred != null)
        return false;
      if((mLeftExpr == null && object.mLeftExpr != null) ||
         (mLeftExpr != null &&
         ! mLeftExpr.equals(object.mLeftExpr))) return false;
      if(mLeftExpr == null && object.mLeftExpr != null)
        return false;
      if((mRightExpr == null && object.mRightExpr != null) ||
         (mRightExpr != null &&
         ! mRightExpr.equals(object.mRightExpr))) return false;
      if(mRightExpr == null && object.mRightExpr != null)
        return false;
      return true;
    }
    return false;
  }

  /**
   * Returns the hash code value for this CondExprImpl.
   * The hash code of a CondExprImpl is defined to be
   * the result of the following calculation:
   *
   * @czt.todo Write the calculation procedure for method hashCode().
   */
  public int hashCode()
  {
    int hashCode = super.hashCode();
    hashCode += "CondExprImpl".hashCode();
    if(mPred != null) {
      hashCode += 31*mPred.hashCode();
    }
    if(mLeftExpr != null) {
      hashCode += 31*mLeftExpr.hashCode();
    }
    if(mRightExpr != null) {
      hashCode += 31*mRightExpr.hashCode();
    }
    return hashCode;
  }

  /**
   * Accepts a visitor.
   */
  public Object accept(net.sourceforge.czt.util.Visitor v)
  {
    if (v instanceof CondExprVisitor)
    {
      CondExprVisitor visitor = (CondExprVisitor) v;
      return visitor.visitCondExpr(this);
    }
    return super.accept(v);
  }

  /**
   * Returns a new object of this class.
   */
  public net.sourceforge.czt.base.ast.Term create(Object[] args) {
    CondExpr zedObject = null;
    try {
      Pred pred = (Pred) args[0];
      Expr leftExpr = (Expr) args[1];
      Expr rightExpr = (Expr) args[2];
      zedObject = new CondExprImpl();
      zedObject.setPred(pred);
      zedObject.setLeftExpr(leftExpr);
      zedObject.setRightExpr(rightExpr);
    } catch (IndexOutOfBoundsException e) {
      throw new IllegalArgumentException();
    } catch (ClassCastException e) {
      throw new IllegalArgumentException();
    }
    return zedObject;
  }

  public Object[] getChildren()
  {
    Object[] erg = { getPred(), getLeftExpr(), getRightExpr() };
    return erg;
  }

  private Pred mPred;

  public Pred getPred()
  {
    return mPred;
  }

  public void setPred(Pred pred)
  {
    mPred = pred;
  }

  private Expr mLeftExpr;

  public Expr getLeftExpr()
  {
    return mLeftExpr;
  }

  public void setLeftExpr(Expr leftExpr)
  {
    mLeftExpr = leftExpr;
  }

  private Expr mRightExpr;

  public Expr getRightExpr()
  {
    return mRightExpr;
  }

  public void setRightExpr(Expr rightExpr)
  {
    mRightExpr = rightExpr;
  }
}
