
/******************************************************************************
DO NOT EDIT THIS FILE!  THIS FILE WAS GENERATED BY GNAST
FROM THE TEMPLATE FILE AstClass.vm.
ANY MODIFICATIONS TO THIS FILE WILL BE LOST UPON REGENERATION.

-------------------------------------------------------------------------------

Copyright 2003, 2004, 2005 Mark Utting
This file is part of the czt project.

The czt project contains free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

The czt project is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with czt; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
******************************************************************************/

package net.sourceforge.czt.circus.impl;

import java.util.*;
import java.util.logging.*;

import net.sourceforge.czt.base.ast.*;
import net.sourceforge.czt.base.impl.*;
import net.sourceforge.czt.base.visitor.*;
import net.sourceforge.czt.util.Visitor;
import net.sourceforge.czt.z.ast.*;
import net.sourceforge.czt.z.impl.*;
import net.sourceforge.czt.circus.ast.*;
import net.sourceforge.czt.circus.visitor.*;

import net.sourceforge.czt.circus.visitor.InterleaveActionIteVisitor;

/**
 * An implementation of the interface
 * {@link InterleaveActionIte}.
 *
 * @author Gnast version 0.1
 */
public class InterleaveActionIteImpl
  extends ParActionIteImpl   implements InterleaveActionIte
{
  /**
   * The default constructor.
   *
   * Do not use it explicitly, unless you are extending this class.
   * If you want to create an instance of this class, please use the
   * {@link net.sourceforge.czt.circus.ast.CircusFactory object factory}.
   */
  protected InterleaveActionIteImpl()
  {
  }

  protected InterleaveActionIteImpl(BaseFactory factory)
  {
    super(factory);
  }

  /**
   * Compares the specified object with this InterleaveActionIteImpl
   * for equality.  Returns true if and only if the specified object is
   * also a(n) InterleaveActionIteImpl and all the getter methods except getAnns
   * return equal objects.
   */
  public boolean equals(Object obj)
  {
    if (obj != null) {
      if (this.getClass().equals(obj.getClass()) && super.equals(obj)) {
        InterleaveActionIteImpl object = (InterleaveActionIteImpl) obj;
        return true;
      }
    }
    return false;
  }

  /**
   * Returns the hash code value for this InterleaveActionIteImpl.
   */
  public int hashCode()
  {
    final int constant = 31;

    int hashCode = super.hashCode();
    hashCode += "InterleaveActionIteImpl".hashCode();
    return hashCode;
  }

  /**
   * Accepts a visitor.
   */
  public <R> R accept(net.sourceforge.czt.util.Visitor<R> v)
  {
    if (v instanceof InterleaveActionIteVisitor) {
      InterleaveActionIteVisitor<R> visitor = (InterleaveActionIteVisitor<R>) v;
      return visitor.visitInterleaveActionIte(this);
    }
    return super.accept(v);
  }

  /**
   * Returns a new object of this class.
   */
  public InterleaveActionIteImpl create(Object[] args)
  {
    InterleaveActionIteImpl zedObject = null;
    try {
      CircusAction circusAction = (CircusAction) args[0];
      net.sourceforge.czt.z.ast.DeclList declList = (net.sourceforge.czt.z.ast.DeclList) args[1];
      NameSet nameSet = (NameSet) args[2];
      zedObject = new InterleaveActionIteImpl(getFactory());
      zedObject.setCircusAction(circusAction);
      zedObject.setDeclList(declList);
      zedObject.setNameSet(nameSet);
    }
    catch (IndexOutOfBoundsException e) {
      throw new IllegalArgumentException();
    }
    catch (ClassCastException e) {
      throw new IllegalArgumentException();
    }
    return zedObject;
  }

  public Object[] getChildren()
  {
    Object[] erg = { getCircusAction(), getDeclList(), getNameSet() };
    return erg;
  }
}
