src/net/sourceforge/czt/scanner/Unicode2Latex.java: src/net/sourceforge/czt/scanner/unicode2latex.cup
	cd src/net/sourceforge/czt/scanner; java java_cup.Main -parser Unicode2Latex < unicode2latex.cup

clean:
	rm -f src/net/sourceforge/czt/scanner/Unicode2Latex.java
	rm -f src/net/sourceforge/czt/scanner/sym.java
