
/******************************************************************************
DO NOT EDIT THIS FILE!  THIS FILE WAS GENERATED BY GNAST
FROM THE TEMPLATE FILE AstClass.vm.
ANY MODIFICATIONS TO THIS FILE WILL BE LOST UPON REGENERATION.

-------------------------------------------------------------------------------

Copyright 2003, 2004, 2005 Mark Utting
This file is part of the czt project.

The czt project contains free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

The czt project is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with czt; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
******************************************************************************/

package net.sourceforge.czt.zpatt.impl;

import java.util.*;
import java.util.logging.*;

import net.sourceforge.czt.base.impl.*;
import net.sourceforge.czt.util.TypesafeList;
import net.sourceforge.czt.z.ast.*;
import net.sourceforge.czt.z.impl.*;
import net.sourceforge.czt.zpatt.ast.*;
import net.sourceforge.czt.zpatt.visitor.*;

import net.sourceforge.czt.zpatt.visitor.JokersVisitor;

/**
 * An implementation of the interface
 * {@link Jokers}.
 *
 * @author Gnast version 0.1
 */
public class JokersImpl
  extends ParaImpl   implements Jokers
{
  /**
   * The default constructor.
   *
   * Do not use it explicitly, unless you are extending this class.
   * If you want to create an instance of this class, please use the
   * {@link net.sourceforge.czt.zpatt.ast.ZpattFactory object factory}.
   */
  protected JokersImpl()
  {
  }

  /**
   * Compares the specified object with this JokersImpl
   * for equality.  Returns true if and only if the specified object is
   * also a(n) JokersImpl and all the getter methods except getAnns
   * return equal objects.
   */
  public boolean equals(Object obj)
  {
    if (obj != null) {
      if (this.getClass().equals(obj.getClass()) && super.equals(obj)) {
        JokersImpl object = (JokersImpl) obj;
        if (name_ != null) {
          if (!name_.equals(object.name_)) {
            return false;
          }
        }
        else {
          if (object.name_ != null) {
            return false;
          }
        }
        if (kind_ != null) {
          if (!kind_.equals(object.kind_)) {
            return false;
          }
        }
        else {
          if (object.kind_ != null) {
            return false;
          }
        }
        return true;
      }
    }
    return false;
  }

  /**
   * Returns the hash code value for this JokersImpl.
   */
  public int hashCode()
  {
    final int constant = 31;

    int hashCode = super.hashCode();
    hashCode += "JokersImpl".hashCode();
    if (name_ != null) {
      hashCode += constant * name_.hashCode();
    }
    if (kind_ != null) {
      hashCode += constant * kind_.hashCode();
    }
    return hashCode;
  }

  /**
   * Accepts a visitor.
   */
  public Object accept(net.sourceforge.czt.util.Visitor v)
  {
    if (v instanceof JokersVisitor) {
      JokersVisitor visitor = (JokersVisitor) v;
      return visitor.visitJokers(this);
    }
    return super.accept(v);
  }

  /**
   * Returns a new object of this class.
   */
  public net.sourceforge.czt.base.ast.Term create(Object[] args)
  {
    Jokers zedObject = null;
    try {
      java.util.List name = (java.util.List) args[0];
      String kind = (String) args[1];
      zedObject = new JokersImpl();
      if (name != null) {
        zedObject.getName().addAll(name);
      }
      zedObject.setKind(kind);
    }
    catch (IndexOutOfBoundsException e) {
      throw new IllegalArgumentException();
    }
    catch (ClassCastException e) {
      throw new IllegalArgumentException();
    }
    return zedObject;
  }

  public Object[] getChildren()
  {
    Object[] erg = { getName(), getKind() };
    return erg;
  }


  private net.sourceforge.czt.base.ast.ListTerm name_ =
    new net.sourceforge.czt.base.impl.ListTermImpl(String.class);

  public net.sourceforge.czt.base.ast.ListTerm getName()
  {
    return name_;
  }

  private String kind_;

  public String getKind()
  {
    return kind_;
  }

  public void setKind(String kind)
  {
    kind_ = kind;
  }
}
