
/******************************************************************************
DO NOT EDIT THIS FILE!  THIS FILE WAS GENERATED BY GNAST
FROM THE TEMPLATE FILE AstClass.vm.
ANY MODIFICATIONS TO THIS FILE WILL BE LOST UPON REGENERATION.

-------------------------------------------------------------------------------

Copyright 2003, 2004, 2005 Mark Utting
This file is part of the czt project.

The czt project contains free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

The czt project is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with czt; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
******************************************************************************/

package net.sourceforge.czt.zpatt.impl;

import java.util.*;
import java.util.logging.*;

import net.sourceforge.czt.base.impl.*;
import net.sourceforge.czt.util.TypesafeList;
import net.sourceforge.czt.z.ast.*;
import net.sourceforge.czt.z.impl.*;
import net.sourceforge.czt.zpatt.ast.*;
import net.sourceforge.czt.zpatt.visitor.*;

import net.sourceforge.czt.zpatt.visitor.JokerExprBindingVisitor;

/**
 * An implementation of the interface
 * {@link JokerExprBinding}.
 *
 * @author Gnast version 0.1
 */
public class JokerExprBindingImpl
  extends BindingImpl   implements JokerExprBinding
{
  /**
   * The default constructor.
   *
   * Do not use it explicitly, unless you are extending this class.
   * If you want to create an instance of this class, please use the
   * {@link net.sourceforge.czt.zpatt.ast.ZpattFactory object factory}.
   */
  protected JokerExprBindingImpl()
  {
  }

  /**
   * Compares the specified object with this JokerExprBindingImpl
   * for equality.  Returns true if and only if the specified object is
   * also a(n) JokerExprBindingImpl and all the getter methods except getAnns
   * return equal objects.
   */
  public boolean equals(Object obj)
  {
    if (obj != null) {
      if (this.getClass().equals(obj.getClass()) && super.equals(obj)) {
        JokerExprBindingImpl object = (JokerExprBindingImpl) obj;
        if (jokerExpr_ != null) {
          if (!jokerExpr_.equals(object.jokerExpr_)) {
            return false;
          }
        }
        else {
          if (object.jokerExpr_ != null) {
            return false;
          }
        }
        if (expr_ != null) {
          if (!expr_.equals(object.expr_)) {
            return false;
          }
        }
        else {
          if (object.expr_ != null) {
            return false;
          }
        }
        return true;
      }
    }
    return false;
  }

  /**
   * Returns the hash code value for this JokerExprBindingImpl.
   */
  public int hashCode()
  {
    final int constant = 31;

    int hashCode = super.hashCode();
    hashCode += "JokerExprBindingImpl".hashCode();
    if (jokerExpr_ != null) {
      hashCode += constant * jokerExpr_.hashCode();
    }
    if (expr_ != null) {
      hashCode += constant * expr_.hashCode();
    }
    return hashCode;
  }

  /**
   * Accepts a visitor.
   */
  public Object accept(net.sourceforge.czt.util.Visitor v)
  {
    if (v instanceof JokerExprBindingVisitor) {
      JokerExprBindingVisitor visitor = (JokerExprBindingVisitor) v;
      return visitor.visitJokerExprBinding(this);
    }
    return super.accept(v);
  }

  /**
   * Returns a new object of this class.
   */
  public net.sourceforge.czt.base.ast.Term create(Object[] args)
  {
    JokerExprBinding zedObject = null;
    try {
      JokerExpr jokerExpr = (JokerExpr) args[0];
      net.sourceforge.czt.z.ast.Expr expr = (net.sourceforge.czt.z.ast.Expr) args[1];
      zedObject = new JokerExprBindingImpl();
      zedObject.setJokerExpr(jokerExpr);
      zedObject.setExpr(expr);
    }
    catch (IndexOutOfBoundsException e) {
      throw new IllegalArgumentException();
    }
    catch (ClassCastException e) {
      throw new IllegalArgumentException();
    }
    return zedObject;
  }

  public Object[] getChildren()
  {
    Object[] erg = { getJokerExpr(), getExpr() };
    return erg;
  }

  private JokerExpr jokerExpr_;

  public JokerExpr getJokerExpr()
  {
    return jokerExpr_;
  }

  public void setJokerExpr(JokerExpr jokerExpr)
  {
    jokerExpr_ = jokerExpr;
  }

  private net.sourceforge.czt.z.ast.Expr expr_;

  public net.sourceforge.czt.z.ast.Expr getExpr()
  {
    return expr_;
  }

  public void setExpr(net.sourceforge.czt.z.ast.Expr expr)
  {
    expr_ = expr;
  }
}
