
/******************************************************************************
DO NOT EDIT THIS FILE!  THIS FILE WAS GENERATED BY GNAST
FROM THE TEMPLATE FILE AstClass.vm.
ANY MODIFICATIONS TO THIS FILE WILL BE LOST UPON REGENERATION.

-------------------------------------------------------------------------------

Copyright 2003, 2004, 2005 Mark Utting
This file is part of the czt project.

The czt project contains free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

The czt project is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with czt; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
******************************************************************************/

package net.sourceforge.czt.z.impl;

import java.util.*;
import java.util.logging.*;

import net.sourceforge.czt.base.ast.*;
import net.sourceforge.czt.base.impl.*;
import net.sourceforge.czt.base.visitor.*;
import net.sourceforge.czt.util.Visitor;
import net.sourceforge.czt.z.ast.*;
import net.sourceforge.czt.z.visitor.*;

import net.sourceforge.czt.z.visitor.Expr0NVisitor;

/**
 * An implementation of the interface
 * {@link Expr0N}.
 *
 * @author Gnast version 0.1
 */
public abstract class Expr0NImpl
  extends ExprImpl   implements Expr0N
{
  /**
   * The default constructor.
   *
   * Do not use it explicitly, unless you are extending this class.
   * If you want to create an instance of this class, please use the
   * {@link net.sourceforge.czt.z.ast.ZFactory object factory}.
   */
  protected Expr0NImpl()
  {
  }

  protected Expr0NImpl(BaseFactory factory)
  {
    super(factory);
  }

  /**
   * Compares the specified object with this Expr0NImpl
   * for equality.  Returns true if and only if the specified object is
   * also a(n) Expr0NImpl and all the getter methods except getAnns
   * return equal objects.
   */
  public boolean equals(Object obj)
  {
    if (obj != null) {
      if (this.getClass().equals(obj.getClass()) && super.equals(obj)) {
        Expr0NImpl object = (Expr0NImpl) obj;
        if (exprList_ != null) {
          if (!exprList_.equals(object.exprList_)) {
            return false;
          }
        }
        else {
          if (object.exprList_ != null) {
            return false;
          }
        }
        return true;
      }
    }
    return false;
  }

  /**
   * Returns the hash code value for this Expr0NImpl.
   */
  public int hashCode()
  {
    final int constant = 31;

    int hashCode = super.hashCode();
    hashCode += "Expr0NImpl".hashCode();
    if (exprList_ != null) {
      hashCode += constant * exprList_.hashCode();
    }
    return hashCode;
  }

  /**
   * Accepts a visitor.
   */
  public <R> R accept(net.sourceforge.czt.util.Visitor<R> v)
  {
    if (v instanceof Expr0NVisitor) {
      Expr0NVisitor<R> visitor = (Expr0NVisitor<R>) v;
      return visitor.visitExpr0N(this);
    }
    return super.accept(v);
  }


  private ExprList exprList_;

  public ExprList getExprList()
  {
    return exprList_;
  }

  public void setExprList(ExprList exprList)
  {
    exprList_ = exprList;
  }
  /**
   * This is a convenience method.
   * It returns a ZExprList if #getExprList
   * returns an instance of ZExprList
   * and throws an UnsupportedAstClassException otherwise.
   */
  public ZExprList getZExprList()
  {
    ExprList object = getExprList();
    if (object instanceof ZExprList) {
      return (ZExprList) object;
    }
    throw new net.sourceforge.czt.base.util.UnsupportedAstClassException();
  }
}
