
/******************************************************************************
DO NOT EDIT THIS FILE!  THIS FILE WAS GENERATED BY GNAST
FROM THE TEMPLATE FILE AstClass.vm.
ANY MODIFICATIONS TO THIS FILE WILL BE LOST UPON REGENERATION.

-------------------------------------------------------------------------------

Copyright 2003, 2004, 2005 Mark Utting
This file is part of the czt project.

The czt project contains free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

The czt project is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with czt; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
******************************************************************************/

package net.sourceforge.czt.oz.impl;

import java.util.*;
import java.util.logging.*;

import net.sourceforge.czt.base.ast.*;
import net.sourceforge.czt.base.impl.*;
import net.sourceforge.czt.base.visitor.*;
import net.sourceforge.czt.util.Visitor;
import net.sourceforge.czt.z.ast.*;
import net.sourceforge.czt.z.impl.*;
import net.sourceforge.czt.oz.ast.*;
import net.sourceforge.czt.oz.visitor.*;

import net.sourceforge.czt.oz.visitor.OpTextVisitor;

/**
 * An implementation of the interface
 * {@link OpText}.
 *
 * @author Gnast version 0.1
 */
public class OpTextImpl
  extends TermImpl   implements OpText
{
  /**
   * The default constructor.
   *
   * Do not use it explicitly, unless you are extending this class.
   * If you want to create an instance of this class, please use the
   * {@link net.sourceforge.czt.oz.ast.OzFactory object factory}.
   */
  protected OpTextImpl()
  {
  }

  protected OpTextImpl(BaseFactory factory)
  {
    super(factory);
  }

  /**
   * Compares the specified object with this OpTextImpl
   * for equality.  Returns true if and only if the specified object is
   * also a(n) OpTextImpl and all the getter methods except getAnns
   * return equal objects.
   */
  public boolean equals(Object obj)
  {
    if (obj != null) {
      if (this.getClass().equals(obj.getClass()) && super.equals(obj)) {
        OpTextImpl object = (OpTextImpl) obj;
        if (deltaList_ != null) {
          if (!deltaList_.equals(object.deltaList_)) {
            return false;
          }
        }
        else {
          if (object.deltaList_ != null) {
            return false;
          }
        }
        if (schText_ != null) {
          if (!schText_.equals(object.schText_)) {
            return false;
          }
        }
        else {
          if (object.schText_ != null) {
            return false;
          }
        }
        return true;
      }
    }
    return false;
  }

  /**
   * Returns the hash code value for this OpTextImpl.
   */
  public int hashCode()
  {
    final int constant = 31;

    int hashCode = super.hashCode();
    hashCode += "OpTextImpl".hashCode();
    if (deltaList_ != null) {
      hashCode += constant * deltaList_.hashCode();
    }
    if (schText_ != null) {
      hashCode += constant * schText_.hashCode();
    }
    return hashCode;
  }

  /**
   * Accepts a visitor.
   */
  public <R> R accept(net.sourceforge.czt.util.Visitor<R> v)
  {
    if (v instanceof OpTextVisitor) {
      OpTextVisitor<R> visitor = (OpTextVisitor<R>) v;
      return visitor.visitOpText(this);
    }
    return super.accept(v);
  }

  /**
   * Returns a new object of this class.
   */
  public OpTextImpl create(Object[] args)
  {
    OpTextImpl zedObject = null;
    try {
      DeltaList deltaList = (DeltaList) args[0];
      net.sourceforge.czt.z.ast.SchText schText = (net.sourceforge.czt.z.ast.SchText) args[1];
      zedObject = new OpTextImpl(getFactory());
      zedObject.setDeltaList(deltaList);
      zedObject.setSchText(schText);
    }
    catch (IndexOutOfBoundsException e) {
      throw new IllegalArgumentException();
    }
    catch (ClassCastException e) {
      throw new IllegalArgumentException();
    }
    return zedObject;
  }

  public Object[] getChildren()
  {
    Object[] erg = { getDeltaList(), getSchText() };
    return erg;
  }

  private DeltaList deltaList_;

  public DeltaList getDeltaList()
  {
    return deltaList_;
  }

  public void setDeltaList(DeltaList deltaList)
  {
    deltaList_ = deltaList;
  }

  private net.sourceforge.czt.z.ast.SchText schText_;

  public net.sourceforge.czt.z.ast.SchText getSchText()
  {
    return schText_;
  }

  public void setSchText(net.sourceforge.czt.z.ast.SchText schText)
  {
    schText_ = schText;
  }
  /**
   * This is a convenience method.
   * It returns the ZSchText if SchText is an instance of
   * ZSchText and throws an UnsupportedAstClassException otherwise.
   */
  public ZSchText getZSchText()
  {
    SchText schText = getSchText();
    if (schText instanceof ZSchText) {
      return (ZSchText) schText;
    }
    throw new net.sourceforge.czt.base.util.UnsupportedAstClassException();
  }

}
