
/******************************************************************************
DO NOT EDIT THIS FILE!  THIS FILE WAS GENERATED BY GNAST
FROM THE TEMPLATE FILE AstClass.vm.
ANY MODIFICATIONS TO THIS FILE WILL BE LOST UPON REGENERATION.

-------------------------------------------------------------------------------

Copyright 2003, 2004, 2005 Mark Utting
This file is part of the czt project.

The czt project contains free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

The czt project is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with czt; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
******************************************************************************/

package net.sourceforge.czt.oz.impl;

import java.util.*;
import java.util.logging.*;

import net.sourceforge.czt.base.ast.*;
import net.sourceforge.czt.base.impl.*;
import net.sourceforge.czt.base.visitor.*;
import net.sourceforge.czt.util.Visitor;
import net.sourceforge.czt.z.ast.*;
import net.sourceforge.czt.z.impl.*;
import net.sourceforge.czt.oz.ast.*;
import net.sourceforge.czt.oz.visitor.*;

import net.sourceforge.czt.oz.visitor.ClassRefVisitor;

/**
 * An implementation of the interface
 * {@link ClassRef}.
 *
 * @author Gnast version 0.1
 */
public class ClassRefImpl
  extends TermImpl   implements ClassRef
{
  /**
   * The default constructor.
   *
   * Do not use it explicitly, unless you are extending this class.
   * If you want to create an instance of this class, please use the
   * {@link net.sourceforge.czt.oz.ast.OzFactory object factory}.
   */
  protected ClassRefImpl()
  {
  }

  protected ClassRefImpl(BaseFactory factory)
  {
    super(factory);
  }

  /**
   * Compares the specified object with this ClassRefImpl
   * for equality.  Returns true if and only if the specified object is
   * also a(n) ClassRefImpl and all the getter methods except getAnns
   * return equal objects.
   */
  public boolean equals(Object obj)
  {
    if (obj != null) {
      if (this.getClass().equals(obj.getClass()) && super.equals(obj)) {
        ClassRefImpl object = (ClassRefImpl) obj;
        if (refName_ != null) {
          if (!refName_.equals(object.refName_)) {
            return false;
          }
        }
        else {
          if (object.refName_ != null) {
            return false;
          }
        }
        if (type_ != null) {
          if (!type_.equals(object.type_)) {
            return false;
          }
        }
        else {
          if (object.type_ != null) {
            return false;
          }
        }
        if (newOldPair_ != null) {
          if (!newOldPair_.equals(object.newOldPair_)) {
            return false;
          }
        }
        else {
          if (object.newOldPair_ != null) {
            return false;
          }
        }
        return true;
      }
    }
    return false;
  }

  /**
   * Returns the hash code value for this ClassRefImpl.
   */
  public int hashCode()
  {
    final int constant = 31;

    int hashCode = super.hashCode();
    hashCode += "ClassRefImpl".hashCode();
    if (refName_ != null) {
      hashCode += constant * refName_.hashCode();
    }
    if (type_ != null) {
      hashCode += constant * type_.hashCode();
    }
    if (newOldPair_ != null) {
      hashCode += constant * newOldPair_.hashCode();
    }
    return hashCode;
  }

  /**
   * Accepts a visitor.
   */
  public <R> R accept(net.sourceforge.czt.util.Visitor<R> v)
  {
    if (v instanceof ClassRefVisitor) {
      ClassRefVisitor<R> visitor = (ClassRefVisitor<R>) v;
      return visitor.visitClassRef(this);
    }
    return super.accept(v);
  }

  /**
   * Returns a new object of this class.
   */
  public ClassRefImpl create(Object[] args)
  {
    ClassRefImpl zedObject = null;
    try {
      net.sourceforge.czt.z.ast.RefName refName = (net.sourceforge.czt.z.ast.RefName) args[0];
      java.util.List<Type2> type = (java.util.List<Type2>) args[1];
      java.util.List<NewOldPair> newOldPair = (java.util.List<NewOldPair>) args[2];
      zedObject = new ClassRefImpl(getFactory());
      zedObject.setRefName(refName);
      if (type != null) {
        zedObject.getType().addAll(type);
      }
      if (newOldPair != null) {
        zedObject.getNewOldPair().addAll(newOldPair);
      }
    }
    catch (IndexOutOfBoundsException e) {
      throw new IllegalArgumentException();
    }
    catch (ClassCastException e) {
      throw new IllegalArgumentException();
    }
    return zedObject;
  }

  public Object[] getChildren()
  {
    Object[] erg = { getRefName(), getType(), getNewOldPair() };
    return erg;
  }

  private net.sourceforge.czt.z.ast.RefName refName_;

  public net.sourceforge.czt.z.ast.RefName getRefName()
  {
    return refName_;
  }

  public void setRefName(net.sourceforge.czt.z.ast.RefName refName)
  {
    refName_ = refName;
  }


  private ListTerm<net.sourceforge.czt.z.ast.Type2> type_ =
    new ListTermImpl<net.sourceforge.czt.z.ast.Type2>();

  public ListTerm<net.sourceforge.czt.z.ast.Type2> getType()
  {
    return type_;
  }


  private ListTerm<net.sourceforge.czt.z.ast.NewOldPair> newOldPair_ =
    new ListTermImpl<net.sourceforge.czt.z.ast.NewOldPair>();

  public ListTerm<net.sourceforge.czt.z.ast.NewOldPair> getNewOldPair()
  {
    return newOldPair_;
  }
  /**
   * This is a convenience method.
   * It returns the ZRefName if RefName is an instance of
   * ZRefName and throws an UnsupportedAstClassException otherwise.
   */
  public ZRefName getZRefName()
  {
    RefName refName = getRefName();
    if (refName instanceof ZRefName) {
      return (ZRefName) refName;
    }
    throw new net.sourceforge.czt.base.util.UnsupportedAstClassException();
  }

}
