
/*
THIS FILE WAS GENERATED BY GNAST.
ANY MODIFICATIONS TO THIS FILE WILL BE LOST UPON REGENERATION.

************************************************************

Copyright 2003 Mark Utting
This file is part of the czt project.

The czt project contains free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

The czt project is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with czt; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

package net.sourceforge.czt.core.impl;

import java.util.*;
import java.util.logging.*;

import net.sourceforge.czt.core.ast.*;
import net.sourceforge.czt.core.util.*;

/**
 * An implementation of the interface
 * {@link Freetype}.
 *
 * @author Gnast version 0.1
 */
public class FreetypeImpl
extends TermAImpl implements Freetype
{
  private static final Logger sLogger =
    Logger.getLogger("net.sourceforge.czt.core.impl.FreetypeImpl");

  /**
   * The default constructor.
   *
   * Do not use it explicitly, unless you are extending this class.
   * If you want to create an instance of this class, please use the
   * {@link CoreFactory object factory}.
   */
  protected FreetypeImpl() { }

  /**
   * Compares the specified object with this FreetypeImpl
   * for equality.  Returns true if and only if the specified object is
   * also a(n) FreetypeImpl and all the getter methods except getAnns
   * return equal objects.
   */
  public boolean equals(Object obj)
  {
    if(obj != null &&
       this.getClass().equals(obj.getClass()) &&
       super.equals(obj)) {
      FreetypeImpl object = (FreetypeImpl) obj;
      if((mDeclName == null && object.mDeclName != null) ||
         (mDeclName != null &&
         ! mDeclName.equals(object.mDeclName))) return false;
      if(mDeclName == null && object.mDeclName != null)
        return false;
      if((mBranch == null && object.mBranch != null) ||
         (mBranch != null &&
         ! mBranch.equals(object.mBranch))) return false;
      if(mBranch == null && object.mBranch != null)
        return false;
      return true;
    }
    return false;
  }

  /**
   * Returns the hash code value for this FreetypeImpl.
   * The hash code of a FreetypeImpl is defined to be
   * the result of the following calculation:
   *
   * @czt.todo Write the calculation procedure for method hashCode().
   */
  public int hashCode()
  {
    int hashCode = super.hashCode();
    hashCode += "FreetypeImpl".hashCode();
    if(mDeclName != null) {
      hashCode += 31*mDeclName.hashCode();
    }
    if(mBranch != null) {
      hashCode += 31*mBranch.hashCode();
    }
    return hashCode;
  }

  /**
   * Accepts a visitor.
   */
  public Object accept(AstVisitor v) {
    return v.visitFreetype(this);
  }

  /**
   * Returns a new object of this class.
   */
  public Term create(Object[] args) {
    sLogger.entering("FreetypeImpl", "create", args);
    Freetype zedObject = null;
    try {
      DeclName declName = (DeclName) args[0];
      java.util.List branch = (java.util.List) args[1];
      zedObject = new FreetypeImpl();
      zedObject.setDeclName(declName);
      if(branch != null) {
        zedObject.getBranch().addAll(branch);
      }
    } catch (IndexOutOfBoundsException e) {
      throw new IllegalArgumentException();
    } catch (ClassCastException e) {
      throw new IllegalArgumentException();
    }
    sLogger.exiting("FreetypeImpl", "create", zedObject);
    return zedObject;
  }

  public Object[] getChildren()
  {
    sLogger.entering("FreetypeImpl", "getChildren");
    Object[] erg = { getDeclName(), getBranch() };
    sLogger.exiting("FreetypeImpl", "getChildren", erg);
    return erg;
  }

  private DeclName mDeclName;

  public DeclName getDeclName()
  {
    return mDeclName;
  }

  public void setDeclName(DeclName declName)
  {
    mDeclName = declName;
  }

  private java.util.List mBranch = new java.util.Vector();

  public java.util.List getBranch()
  {
    return mBranch;
  }
}
