name: automerge

on:
  pull_request_review:
    types: [submitted]

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: automerge
      - name: automerge
        if: ${{ github.event.review.state == 'approved' }}
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"
